[package]
name = "jsdrop"
version = "0.1.0"
authors = ["omega <398914521@qq.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3.36"